// provided.js - generated by ephemient/aoc2024/Kotlin benchmarks, 2024-12-05 10:55:22.594609063

var providedBenchmarks = ["graalvm","jvm","linuxX64","wasmJs"];

var providedBenchmarkStore = {
  "wasmJs": [
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1199.7456938053097,
        "scoreError": 52.22424437182668,
        "scoreConfidence": [
          1147.521449433483,
          1251.9699381771363
        ],
        "scorePercentiles": {
          "0.00": 1171.4131592920355,
          "25.00": 1171.5760461441214,
          "50.00": 1173.2485056890011,
          "75.00": 1241.1639355246525,
          "90.00": 1306.2753438685208,
          "99.00": 1306.2753438685208,
          "99.90": 1306.2753438685208,
          "99.99": 1306.2753438685208,
          "100.00": 1306.2753438685208
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1306.2753438685208,
            1176.052527180784,
            1173.2485056890011,
            1171.4131592920355,
            1171.7389329962075
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1059.626051694915,
        "scoreError": 16.953505500601082,
        "scoreConfidence": [
          1042.672546194314,
          1076.5795571955161
        ],
        "scorePercentiles": {
          "0.00": 1048.2658093220339,
          "25.00": 1049.3267304025424,
          "50.00": 1051.0640847457626,
          "75.00": 1074.2063564618643,
          "90.00": 1093.9988008474577,
          "99.00": 1093.9988008474577,
          "99.90": 1093.9988008474577,
          "99.99": 1093.9988008474577,
          "100.00": 1093.9988008474577
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1051.0640847457626,
            1054.4139120762711,
            1048.2658093220339,
            1050.3876514830508,
            1093.9988008474577
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2571.895906185567,
        "scoreError": 43.01279879189545,
        "scoreConfidence": [
          2528.8831073936717,
          2614.9087049774625
        ],
        "scorePercentiles": {
          "0.00": 2523.2436417525773,
          "25.00": 2525.837668814433,
          "50.00": 2562.866461340206,
          "75.00": 2622.468865979382,
          "90.00": 2631.9284871134023,
          "99.00": 2631.9284871134023,
          "99.90": 2631.9284871134023,
          "99.99": 2631.9284871134023,
          "100.00": 2631.9284871134023
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2528.431695876289,
            2523.2436417525773,
            2613.009244845361,
            2631.9284871134023,
            2562.866461340206
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2722.633560326087,
        "scoreError": 16.255117478697862,
        "scoreConfidence": [
          2706.378442847389,
          2738.8886778047845
        ],
        "scorePercentiles": {
          "0.00": 2699.5863885869567,
          "25.00": 2705.4535108695654,
          "50.00": 2721.7529375,
          "75.00": 2740.2539211956523,
          "90.00": 2747.136309782609,
          "99.00": 2747.136309782609,
          "99.90": 2747.136309782609,
          "99.99": 2747.136309782609,
          "100.00": 2747.136309782609
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2699.5863885869567,
            2747.136309782609,
            2733.371532608696,
            2711.3206331521737,
            2721.7529375
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 925.5387343984963,
        "scoreError": 5.276266982162235,
        "scoreConfidence": [
          920.2624674163341,
          930.8150013806586
        ],
        "scorePercentiles": {
          "0.00": 921.3042208646616,
          "25.00": 921.3737349624059,
          "50.00": 921.8137518796993,
          "75.00": 931.5662250939849,
          "90.00": 935.0081343984963,
          "99.00": 935.0081343984963,
          "99.90": 935.0081343984963,
          "99.99": 935.0081343984963,
          "100.00": 935.0081343984963
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            921.4432490601504,
            921.3042208646616,
            921.8137518796993,
            935.0081343984963,
            928.1243157894737
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 843.2583838454786,
        "scoreError": 2.5597334477606726,
        "scoreConfidence": [
          840.698650397718,
          845.8181172932393
        ],
        "scorePercentiles": {
          "0.00": 840.0657085162424,
          "25.00": 840.2176417910448,
          "50.00": 843.8149754170325,
          "75.00": 846.0208301141353,
          "90.00": 846.0491799824408,
          "99.00": 846.0491799824408,
          "99.90": 846.0491799824408,
          "99.99": 846.0491799824408,
          "100.00": 846.0491799824408
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            846.0491799824408,
            843.8149754170325,
            840.0657085162424,
            840.3695750658472,
            845.9924802458297
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 14838.275236363635,
        "scoreError": 44.40741702004075,
        "scoreConfidence": [
          14793.867819343595,
          14882.682653383676
        ],
        "scorePercentiles": {
          "0.00": 14776.36906060606,
          "25.00": 14786.210174242424,
          "50.00": 14849.366893939394,
          "75.00": 14884.79446969697,
          "90.00": 14894.802303030303,
          "99.00": 14894.802303030303,
          "99.90": 14894.802303030303,
          "99.99": 14894.802303030303,
          "100.00": 14894.802303030303
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            14894.802303030303,
            14776.36906060606,
            14796.051287878787,
            14849.366893939394,
            14874.786636363637
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1698.8597728695654,
        "scoreError": 4.603601042959288,
        "scoreConfidence": [
          1694.256171826606,
          1703.4633739125247
        ],
        "scorePercentiles": {
          "0.00": 1691.357187826087,
          "25.00": 1693.8584973913044,
          "50.00": 1699.2198939130435,
          "75.00": 1703.680987826087,
          "90.00": 1704.4485982608694,
          "99.00": 1704.4485982608694,
          "99.90": 1704.4485982608694,
          "99.99": 1704.4485982608694,
          "100.00": 1704.4485982608694
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1704.4485982608694,
            1691.357187826087,
            1702.9133773913043,
            1696.3598069565217,
            1699.2198939130435
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1328.0028966261807,
        "scoreError": 4.994328435833793,
        "scoreConfidence": [
          1323.008568190347,
          1332.9972250620144
        ],
        "scorePercentiles": {
          "0.00": 1322.4835870445345,
          "25.00": 1322.5810573549256,
          "50.00": 1327.5929163292847,
          "75.00": 1333.629726045884,
          "90.00": 1335.5735384615384,
          "99.00": 1335.5735384615384,
          "99.90": 1335.5735384615384,
          "99.99": 1335.5735384615384,
          "100.00": 1335.5735384615384
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1322.678527665317,
            1327.5929163292847,
            1331.6859136302294,
            1335.5735384615384,
            1322.4835870445345
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2501.100565989848,
        "scoreError": 18.99881704659838,
        "scoreConfidence": [
          2482.1017489432493,
          2520.0993830364464
        ],
        "scorePercentiles": {
          "0.00": 2487.0191522842642,
          "25.00": 2487.4261865482235,
          "50.00": 2490.9548553299496,
          "75.00": 2519.8478007614212,
          "90.00": 2538.543114213198,
          "99.00": 2538.543114213198,
          "99.90": 2538.543114213198,
          "99.99": 2538.543114213198,
          "100.00": 2538.543114213198
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2538.543114213198,
            2490.9548553299496,
            2487.833220812183,
            2487.0191522842642,
            2501.1524873096446
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "graalvm": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 484.6664546398007,
        "scoreError": 16.163479649499692,
        "scoreConfidence": [
          468.502974990301,
          500.82993428930035
        ],
        "scorePercentiles": {
          "0.0": 477.3998133651551,
          "50.0": 486.3464127369956,
          "90.0": 487.49610331384014,
          "95.0": 487.49610331384014,
          "99.0": 487.49610331384014,
          "99.9": 487.49610331384014,
          "99.99": 487.49610331384014,
          "99.999": 487.49610331384014,
          "99.9999": 487.49610331384014,
          "100.0": 487.49610331384014
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            477.3998133651551,
            486.3464127369956,
            487.49610331384014,
            484.8109413475521,
            487.2790024354603
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 369.36005698089474,
        "scoreError": 9.868477941276602,
        "scoreConfidence": [
          359.49157903961816,
          379.2285349221713
        ],
        "scorePercentiles": {
          "0.0": 365.49706683710735,
          "50.0": 369.82601774491684,
          "90.0": 372.12143154761907,
          "95.0": 372.12143154761907,
          "99.0": 372.12143154761907,
          "99.9": 372.12143154761907,
          "99.99": 372.12143154761907,
          "99.999": 372.12143154761907,
          "99.9999": 372.12143154761907,
          "100.0": 372.12143154761907
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            365.49706683710735,
            369.82601774491684,
            372.12143154761907,
            370.96338019287833,
            368.3923885819521
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 670.504469553638,
        "scoreError": 3.660580521150358,
        "scoreConfidence": [
          666.8438890324877,
          674.1650500747884
        ],
        "scorePercentiles": {
          "0.0": 669.3615886287625,
          "50.0": 670.3834423592493,
          "90.0": 671.7479543317663,
          "95.0": 671.7479543317663,
          "99.0": 671.7479543317663,
          "99.9": 671.7479543317663,
          "99.99": 671.7479543317663,
          "99.999": 671.7479543317663,
          "99.9999": 671.7479543317663,
          "100.0": 671.7479543317663
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            671.7479543317663,
            669.9032947086404,
            670.3834423592493,
            671.126067739772,
            669.3615886287625
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 737.7815053334331,
        "scoreError": 17.54650955974197,
        "scoreConfidence": [
          720.2349957736911,
          755.328014893175
        ],
        "scorePercentiles": {
          "0.0": 731.4816111111111,
          "50.0": 740.364674315322,
          "90.0": 741.5162564862861,
          "95.0": 741.5162564862861,
          "99.0": 741.5162564862861,
          "99.9": 741.5162564862861,
          "99.99": 741.5162564862861,
          "99.999": 741.5162564862861,
          "99.9999": 741.5162564862861,
          "100.0": 741.5162564862861
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            740.364674315322,
            741.1449362962964,
            731.4816111111111,
            741.5162564862861,
            734.4000484581497
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 209.37382946241473,
        "scoreError": 4.562291507145724,
        "scoreConfidence": [
          204.81153795526902,
          213.93612096956045
        ],
        "scorePercentiles": {
          "0.0": 208.29487151187004,
          "50.0": 209.2081300983058,
          "90.0": 211.36532776838547,
          "95.0": 211.36532776838547,
          "99.0": 211.36532776838547,
          "99.9": 211.36532776838547,
          "99.99": 211.36532776838547,
          "99.999": 211.36532776838547,
          "99.9999": 211.36532776838547,
          "100.0": 211.36532776838547
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            209.2081300983058,
            211.36532776838547,
            209.29921155053358,
            208.29487151187004,
            208.70160638297872
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 132.36219637154187,
        "scoreError": 1.6094190911675648,
        "scoreConfidence": [
          130.75277728037432,
          133.97161546270942
        ],
        "scorePercentiles": {
          "0.0": 131.75487406138848,
          "50.0": 132.4010166799047,
          "90.0": 132.74767069285903,
          "95.0": 132.74767069285903,
          "99.0": 132.74767069285903,
          "99.9": 132.74767069285903,
          "99.99": 132.74767069285903,
          "99.999": 132.74767069285903,
          "99.9999": 132.74767069285903,
          "100.0": 132.74767069285903
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            132.4010166799047,
            132.74767069285903,
            131.75487406138848,
            132.7392607830126,
            132.16815964054447
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 6977.131145684124,
        "scoreError": 220.7138688394917,
        "scoreConfidence": [
          6756.417276844632,
          7197.845014523616
        ],
        "scorePercentiles": {
          "0.0": 6921.866924137931,
          "50.0": 6977.1815625,
          "90.0": 7065.904070422535,
          "95.0": 7065.904070422535,
          "99.0": 7065.904070422535,
          "99.9": 7065.904070422535,
          "99.99": 7065.904070422535,
          "99.999": 7065.904070422535,
          "99.9999": 7065.904070422535,
          "100.0": 7065.904070422535
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            6989.020847222222,
            6931.682324137931,
            7065.904070422535,
            6977.1815625,
            6921.866924137931
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 821.6659379400862,
        "scoreError": 10.281104243056042,
        "scoreConfidence": [
          811.3848336970302,
          831.9470421831422
        ],
        "scorePercentiles": {
          "0.0": 818.8870941080196,
          "50.0": 821.8346696795398,
          "90.0": 825.1888382838284,
          "95.0": 825.1888382838284,
          "99.0": 825.1888382838284,
          "99.9": 825.1888382838284,
          "99.99": 825.1888382838284,
          "99.999": 825.1888382838284,
          "99.9999": 825.1888382838284,
          "100.0": 825.1888382838284
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            823.2016658436214,
            819.2174217854218,
            818.8870941080196,
            821.8346696795398,
            825.1888382838284
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 657.1708539879138,
        "scoreError": 7.130477649914286,
        "scoreConfidence": [
          650.0403763379995,
          664.3013316378281
        ],
        "scorePercentiles": {
          "0.0": 655.0985455140799,
          "50.0": 657.3498580814718,
          "90.0": 659.233779314888,
          "95.0": 659.233779314888,
          "99.0": 659.233779314888,
          "99.9": 659.233779314888,
          "99.99": 659.233779314888,
          "99.999": 659.233779314888,
          "99.9999": 659.233779314888,
          "100.0": 659.233779314888
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            655.4861146788991,
            658.6859723502304,
            659.233779314888,
            657.3498580814718,
            655.0985455140799
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1241.9050509151803,
        "scoreError": 12.828197387632422,
        "scoreConfidence": [
          1229.0768535275479,
          1254.7332483028126
        ],
        "scorePercentiles": {
          "0.0": 1239.4384076827757,
          "50.0": 1240.8535799256506,
          "90.0": 1247.7288428927682,
          "95.0": 1247.7288428927682,
          "99.0": 1247.7288428927682,
          "99.9": 1247.7288428927682,
          "99.99": 1247.7288428927682,
          "99.999": 1247.7288428927682,
          "99.9999": 1247.7288428927682,
          "100.0": 1247.7288428927682
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1241.3132282878412,
            1240.191195786865,
            1240.8535799256506,
            1239.4384076827757,
            1247.7288428927682
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "linuxX64": [
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1044.8816315920399,
        "scoreError": 60.34492237799704,
        "scoreConfidence": [
          984.5367092140428,
          1105.226553970037
        ],
        "scorePercentiles": {
          "0.00": 1004.5139912935323,
          "25.00": 1005.3280422885572,
          "50.00": 1009.4785373134328,
          "75.00": 1102.1367680348258,
          "90.00": 1165.4546890547265,
          "99.00": 1165.4546890547265,
          "99.90": 1165.4546890547265,
          "99.99": 1165.4546890547265,
          "100.00": 1165.4546890547265
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1165.4546890547265,
            1038.8188470149253,
            1009.4785373134328,
            1004.5139912935323,
            1006.1420932835821
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 892.8988862068966,
        "scoreError": 8.1177707213344,
        "scoreConfidence": [
          884.7811154855622,
          901.016656928231
        ],
        "scorePercentiles": {
          "0.00": 882.2947422867514,
          "25.00": 883.9497313974591,
          "50.00": 892.8375226860254,
          "75.00": 901.8787227767696,
          "90.00": 904.7199754990926,
          "99.00": 904.7199754990926,
          "99.90": 904.7199754990926,
          "99.99": 904.7199754990926,
          "100.00": 904.7199754990926
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            882.2947422867514,
            892.8375226860254,
            904.7199754990926,
            899.0374700544464,
            885.6047205081669
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2559.740935384615,
        "scoreError": 11.8317276267644,
        "scoreConfidence": [
          2547.9092077578507,
          2571.5726630113795
        ],
        "scorePercentiles": {
          "0.00": 2540.6593128205127,
          "25.00": 2545.8044474358976,
          "50.00": 2565.0388025641028,
          "75.00": 2571.0284897435895,
          "90.00": 2572.5332128205127,
          "99.00": 2572.5332128205127,
          "99.90": 2572.5332128205127,
          "99.99": 2572.5332128205127,
          "100.00": 2572.5332128205127
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2550.9495820512825,
            2572.5332128205127,
            2540.6593128205127,
            2569.5237666666667,
            2565.0388025641028
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2703.6244237837836,
        "scoreError": 21.919553220092343,
        "scoreConfidence": [
          2681.704870563691,
          2725.543977003876
        ],
        "scorePercentiles": {
          "0.00": 2678.3440108108107,
          "25.00": 2682.354416216216,
          "50.00": 2700.6779756756755,
          "75.00": 2726.3676554054055,
          "90.00": 2742.510845945946,
          "99.00": 2742.510845945946,
          "99.90": 2742.510845945946,
          "99.99": 2742.510845945946,
          "100.00": 2742.510845945946
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2678.3440108108107,
            2700.6779756756755,
            2686.3648216216216,
            2742.510845945946,
            2710.224464864865
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 736.7895863095239,
        "scoreError": 6.11263332739782,
        "scoreConfidence": [
          730.6769529821261,
          742.9022196369217
        ],
        "scorePercentiles": {
          "0.00": 728.9966205357143,
          "25.00": 729.1650900297618,
          "50.00": 741.2527537202382,
          "75.00": 742.1824988839286,
          "90.00": 742.4223727678572,
          "99.00": 742.4223727678572,
          "99.90": 742.4223727678572,
          "99.99": 742.4223727678572,
          "100.00": 742.4223727678572
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            729.3335595238094,
            741.2527537202382,
            728.9966205357143,
            742.4223727678572,
            741.942625
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 477.00025515239474,
        "scoreError": 0.6883877611024014,
        "scoreConfidence": [
          476.31186739129237,
          477.6886429134971
        ],
        "scorePercentiles": {
          "0.00": 475.93141170778904,
          "25.00": 476.1619646831156,
          "50.00": 477.47393517174646,
          "75.00": 477.60170561199806,
          "90.00": 477.6627624576681,
          "99.00": 477.6627624576681,
          "99.90": 477.6627624576681,
          "99.99": 477.6627624576681,
          "100.00": 477.6627624576681
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            477.47393517174646,
            476.3925176584422,
            477.6627624576681,
            475.93141170778904,
            477.540648766328
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 15774.75966984127,
        "scoreError": 268.30342261045274,
        "scoreConfidence": [
          15506.456247230819,
          16043.063092451723
        ],
        "scorePercentiles": {
          "0.00": 15371.18126984127,
          "25.00": 15539.617857142857,
          "50.00": 15724.607507936507,
          "75.00": 16034.977563492062,
          "90.00": 16221.40134920635,
          "99.00": 16221.40134920635,
          "99.90": 16221.40134920635,
          "99.99": 16221.40134920635,
          "100.00": 16221.40134920635
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            15724.607507936507,
            15708.054444444444,
            16221.40134920635,
            15848.553777777777,
            15371.18126984127
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1443.5655687861272,
        "scoreError": 19.65837878077839,
        "scoreConfidence": [
          1423.9071900053489,
          1463.2239475669055
        ],
        "scorePercentiles": {
          "0.00": 1423.0681343930637,
          "25.00": 1423.8476423410405,
          "50.00": 1435.5948497109828,
          "75.00": 1467.2688547687862,
          "90.00": 1472.0594378612716,
          "99.00": 1472.0594378612716,
          "99.90": 1472.0594378612716,
          "99.99": 1472.0594378612716,
          "100.00": 1472.0594378612716
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1435.5948497109828,
            1462.4782716763007,
            1472.0594378612716,
            1424.6271502890172,
            1423.0681343930637
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1015.7674972515857,
        "scoreError": 4.425716521531515,
        "scoreConfidence": [
          1011.3417807300542,
          1020.1932137731172
        ],
        "scorePercentiles": {
          "0.00": 1010.2136797040168,
          "25.00": 1010.5667764270613,
          "50.00": 1016.5334809725159,
          "75.00": 1020.5852262156449,
          "90.00": 1021.1423879492601,
          "99.00": 1021.1423879492601,
          "99.90": 1021.1423879492601,
          "99.99": 1021.1423879492601,
          "100.00": 1021.1423879492601
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1010.9198731501057,
            1021.1423879492601,
            1010.2136797040168,
            1016.5334809725159,
            1020.0280644820297
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2307.477788558352,
        "scoreError": 32.63418412231034,
        "scoreConfidence": [
          2274.843604436042,
          2340.1119726806623
        ],
        "scorePercentiles": {
          "0.00": 2263.278256292906,
          "25.00": 2269.4120995423336,
          "50.00": 2321.5302745995423,
          "75.00": 2338.517234553776,
          "90.00": 2353.4655514874144,
          "99.00": 2353.4655514874144,
          "99.90": 2353.4655514874144,
          "99.99": 2353.4655514874144,
          "100.00": 2353.4655514874144
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2263.278256292906,
            2353.4655514874144,
            2323.568917620137,
            2275.5459427917617,
            2321.5302745995423
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvm": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 288.89652925639325,
        "scoreError": 19.412837252742975,
        "scoreConfidence": [
          269.4836920036503,
          308.3093665091362
        ],
        "scorePercentiles": {
          "0.0": 284.94056422671605,
          "50.0": 285.77073285714283,
          "90.0": 295.6491046408513,
          "95.0": 295.6491046408513,
          "99.0": 295.6491046408513,
          "99.9": 295.6491046408513,
          "99.99": 295.6491046408513,
          "99.999": 295.6491046408513,
          "99.9999": 295.6491046408513,
          "100.0": 295.6491046408513
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            295.6491046408513,
            285.77073285714283,
            292.97221177504395,
            285.15003278221207,
            284.94056422671605
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 159.47382875232694,
        "scoreError": 10.840612392262937,
        "scoreConfidence": [
          148.633216360064,
          170.31444114458986
        ],
        "scorePercentiles": {
          "0.0": 157.70748912015137,
          "50.0": 158.67823496747582,
          "90.0": 164.4429811072778,
          "95.0": 164.4429811072778,
          "99.0": 164.4429811072778,
          "99.9": 164.4429811072778,
          "99.99": 164.4429811072778,
          "99.999": 164.4429811072778,
          "99.9999": 164.4429811072778,
          "100.0": 164.4429811072778
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            158.6946528637157,
            164.4429811072778,
            157.70748912015137,
            158.67823496747582,
            157.84578570301403
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 322.3152164124384,
        "scoreError": 15.835021204388317,
        "scoreConfidence": [
          306.4801952080501,
          338.15023761682676
        ],
        "scorePercentiles": {
          "0.0": 319.85671707161123,
          "50.0": 320.4406303651505,
          "90.0": 329.584742339374,
          "95.0": 329.584742339374,
          "99.0": 329.584742339374,
          "99.9": 329.584742339374,
          "99.99": 329.584742339374,
          "99.999": 329.584742339374,
          "99.9999": 329.584742339374,
          "100.0": 329.584742339374
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            329.584742339374,
            321.52837704918034,
            320.1656152368758,
            319.85671707161123,
            320.4406303651505
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 382.6141336692313,
        "scoreError": 10.73645622257657,
        "scoreConfidence": [
          371.87767744665473,
          393.3505898918079
        ],
        "scorePercentiles": {
          "0.0": 379.6149457305503,
          "50.0": 381.9808304696449,
          "90.0": 387.0637275541796,
          "95.0": 387.0637275541796,
          "99.0": 387.0637275541796,
          "99.9": 387.0637275541796,
          "99.99": 387.0637275541796,
          "99.999": 387.0637275541796,
          "99.9999": 387.0637275541796,
          "100.0": 387.0637275541796
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            381.320187571483,
            381.9808304696449,
            379.6149457305503,
            383.09097702029874,
            387.0637275541796
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 119.53667659542887,
        "scoreError": 1.1149593013017594,
        "scoreConfidence": [
          118.42171729412712,
          120.65163589673062
        ],
        "scorePercentiles": {
          "0.0": 119.24914355550257,
          "50.0": 119.56165188284518,
          "90.0": 119.96128639961621,
          "95.0": 119.96128639961621,
          "99.0": 119.96128639961621,
          "99.9": 119.96128639961621,
          "99.99": 119.96128639961621,
          "99.999": 119.96128639961621,
          "99.9999": 119.96128639961621,
          "100.0": 119.96128639961621
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            119.62687716780289,
            119.28442397137746,
            119.96128639961621,
            119.56165188284518,
            119.24914355550257
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 79.54585250863302,
        "scoreError": 2.235270849038242,
        "scoreConfidence": [
          77.31058165959477,
          81.78112335767126
        ],
        "scorePercentiles": {
          "0.0": 78.8149572892041,
          "50.0": 79.58881109254396,
          "90.0": 80.39851941162286,
          "95.0": 80.39851941162286,
          "99.0": 80.39851941162286,
          "99.9": 80.39851941162286,
          "99.99": 80.39851941162286,
          "99.999": 80.39851941162286,
          "99.9999": 80.39851941162286,
          "100.0": 80.39851941162286
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            80.39851941162286,
            79.58881109254396,
            79.27477443132283,
            79.65220031847134,
            78.8149572892041
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1941.924787599623,
        "scoreError": 31.018218246723244,
        "scoreConfidence": [
          1910.9065693528996,
          1972.9430058463463
        ],
        "scorePercentiles": {
          "0.0": 1931.7105347490347,
          "50.0": 1942.5237398058252,
          "90.0": 1953.0206354775828,
          "95.0": 1953.0206354775828,
          "99.0": 1953.0206354775828,
          "99.9": 1953.0206354775828,
          "99.99": 1953.0206354775828,
          "99.999": 1953.0206354775828,
          "99.9999": 1953.0206354775828,
          "100.0": 1953.0206354775828
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1937.2697988394584,
            1953.0206354775828,
            1942.5237398058252,
            1931.7105347490347,
            1945.0992291262137
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 558.4538045655412,
        "scoreError": 7.299163145425138,
        "scoreConfidence": [
          551.154641420116,
          565.7529677109663
        ],
        "scorePercentiles": {
          "0.0": 557.1158574610245,
          "50.0": 557.6247491638796,
          "90.0": 561.6840527793374,
          "95.0": 561.6840527793374,
          "99.0": 561.6840527793374,
          "99.9": 561.6840527793374,
          "99.99": 561.6840527793374,
          "99.999": 561.6840527793374,
          "99.9999": 561.6840527793374,
          "100.0": 561.6840527793374
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            561.6840527793374,
            557.1158574610245,
            557.6247491638796,
            558.5913417085427,
            557.253021714922
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 377.71642073847926,
        "scoreError": 4.956471731219425,
        "scoreConfidence": [
          372.7599490072598,
          382.6728924696987
        ],
        "scorePercentiles": {
          "0.0": 376.0003374671176,
          "50.0": 377.9250336229694,
          "90.0": 379.36728858551385,
          "95.0": 379.36728858551385,
          "99.0": 379.36728858551385,
          "99.9": 379.36728858551385,
          "99.99": 379.36728858551385,
          "99.999": 379.36728858551385,
          "99.9999": 379.36728858551385,
          "100.0": 379.36728858551385
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            379.36728858551385,
            378.3167420574887,
            377.9250336229694,
            376.0003374671176,
            376.97270195930673
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day5Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1046.9898236853676,
        "scoreError": 19.552473880338482,
        "scoreConfidence": [
          1027.437349805029,
          1066.5422975657061
        ],
        "scorePercentiles": {
          "0.0": 1042.1001979166667,
          "50.0": 1045.0208517745302,
          "90.0": 1055.2100221518988,
          "95.0": 1055.2100221518988,
          "99.0": 1055.2100221518988,
          "99.9": 1055.2100221518988,
          "99.99": 1055.2100221518988,
          "99.999": 1055.2100221518988,
          "99.9999": 1055.2100221518988,
          "100.0": 1055.2100221518988
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1055.2100221518988,
            1044.4585041753653,
            1042.1001979166667,
            1048.1595424083769,
            1045.0208517745302
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
