// provided.js - generated by ephemient/aoc2024/Kotlin benchmarks, 2024-12-02 17:17:46.428998156

var providedBenchmarks = ["graalvm","jvm","linuxX64","wasmJs"];

var providedBenchmarkStore = {
  "graalvm": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 497.4733903717937,
        "scoreError": 48.4823473871621,
        "scoreConfidence": [
          448.9910429846316,
          545.9557377589558
        ],
        "scorePercentiles": {
          "0.0": 475.907662226451,
          "50.0": 500.6454994994995,
          "90.0": 508.85085961342827,
          "95.0": 508.85085961342827,
          "99.0": 508.85085961342827,
          "99.9": 508.85085961342827,
          "99.99": 508.85085961342827,
          "99.999": 508.85085961342827,
          "99.9999": 508.85085961342827,
          "100.0": 508.85085961342827
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            475.907662226451,
            499.4160279580629,
            502.54690256152685,
            500.6454994994995,
            508.85085961342827
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 366.53046022598016,
        "scoreError": 10.136508115712966,
        "scoreConfidence": [
          356.3939521102672,
          376.6669683416931
        ],
        "scorePercentiles": {
          "0.0": 363.43970021802323,
          "50.0": 367.55560088202867,
          "90.0": 369.77832754158965,
          "95.0": 369.77832754158965,
          "99.0": 369.77832754158965,
          "99.9": 369.77832754158965,
          "99.99": 369.77832754158965,
          "99.999": 369.77832754158965,
          "99.9999": 369.77832754158965,
          "100.0": 369.77832754158965
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            369.77832754158965,
            363.43970021802323,
            367.55560088202867,
            364.2265445941027,
            367.65212789415654
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 622.7524346349179,
        "scoreError": 46.14995555293035,
        "scoreConfidence": [
          576.6024790819876,
          668.9023901878483
        ],
        "scorePercentiles": {
          "0.0": 612.2784920440637,
          "50.0": 617.4825135802469,
          "90.0": 642.5950976236352,
          "95.0": 642.5950976236352,
          "99.0": 642.5950976236352,
          "99.9": 642.5950976236352,
          "99.99": 642.5950976236352,
          "99.999": 642.5950976236352,
          "99.9999": 642.5950976236352,
          "100.0": 642.5950976236352
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            624.8835677701437,
            617.4825135802469,
            612.2784920440637,
            616.5225021565003,
            642.5950976236352
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 672.2638530179456,
        "scoreError": 4.591946650649352,
        "scoreConfidence": [
          667.6719063672963,
          676.855799668595
        ],
        "scorePercentiles": {
          "0.0": 670.5044329758713,
          "50.0": 672.7996415601883,
          "90.0": 673.5096424242424,
          "95.0": 673.5096424242424,
          "99.0": 673.5096424242424,
          "99.9": 673.5096424242424,
          "99.99": 673.5096424242424,
          "99.999": 673.5096424242424,
          "99.9999": 673.5096424242424,
          "100.0": 673.5096424242424
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            671.638977181208,
            672.7996415601883,
            672.8665709482179,
            673.5096424242424,
            670.5044329758713
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "wasmJs": [
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1191.376893281654,
        "scoreError": 5.175291561774496,
        "scoreConfidence": [
          1186.2016017198796,
          1196.5521848434284
        ],
        "scorePercentiles": {
          "0.00": 1185.6920762273903,
          "25.00": 1186.8756434108527,
          "50.00": 1188.642587855297,
          "75.00": 1197.2452958656331,
          "90.00": 1200.3887932816538,
          "99.00": 1200.3887932816538,
          "99.90": 1200.3887932816538,
          "99.99": 1200.3887932816538,
          "100.00": 1200.3887932816538
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1200.3887932816538,
            1188.0592105943153,
            1194.1017984496125,
            1188.642587855297,
            1185.6920762273903
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1065.661459827214,
        "scoreError": 10.58025469927809,
        "scoreConfidence": [
          1055.0812051279358,
          1076.2417145264922
        ],
        "scorePercentiles": {
          "0.00": 1057.90932937365,
          "25.00": 1058.1020275377969,
          "50.00": 1062.112889848812,
          "75.00": 1074.9951771058315,
          "90.00": 1086.8609708423326,
          "99.00": 1086.8609708423326,
          "99.90": 1086.8609708423326,
          "99.99": 1086.8609708423326,
          "100.00": 1086.8609708423326
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1062.112889848812,
            1058.2947257019437,
            1063.1293833693305,
            1057.90932937365,
            1086.8609708423326
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2619.424772251309,
        "scoreError": 25.26263412690919,
        "scoreConfidence": [
          2594.1621381244,
          2644.6874063782184
        ],
        "scorePercentiles": {
          "0.00": 2596.7710942408376,
          "25.00": 2602.954882198953,
          "50.00": 2610.2256439790576,
          "75.00": 2640.4942264397905,
          "90.00": 2669.91459947644,
          "99.00": 2669.91459947644,
          "99.90": 2669.91459947644,
          "99.99": 2669.91459947644,
          "100.00": 2669.91459947644
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2610.2256439790576,
            2596.7710942408376,
            2669.91459947644,
            2609.1386701570677,
            2611.073853403141
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2785.755405540166,
        "scoreError": 40.02635132511876,
        "scoreConfidence": [
          2745.729054215047,
          2825.781756865285
        ],
        "scorePercentiles": {
          "0.00": 2737.847817174515,
          "25.00": 2746.2891966759003,
          "50.00": 2785.6676204986147,
          "75.00": 2825.265506925208,
          "90.00": 2856.5789252077566,
          "99.00": 2856.5789252077566,
          "99.90": 2856.5789252077566,
          "99.99": 2856.5789252077566,
          "100.00": 2856.5789252077566
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2793.952088642659,
            2856.5789252077566,
            2785.6676204986147,
            2754.7305761772855,
            2737.847817174515
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvm": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 282.4145438491026,
        "scoreError": 8.664242220201077,
        "scoreConfidence": [
          273.7503016289015,
          291.07878606930365
        ],
        "scorePercentiles": {
          "0.0": 280.4176680684048,
          "50.0": 281.2933155230596,
          "90.0": 286.0185028538813,
          "95.0": 286.0185028538813,
          "99.0": 286.0185028538813,
          "99.9": 286.0185028538813,
          "99.99": 286.0185028538813,
          "99.999": 286.0185028538813,
          "99.9999": 286.0185028538813,
          "100.0": 286.0185028538813
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            286.0185028538813,
            280.4176680684048,
            283.1463362581376,
            281.2933155230596,
            281.1968965420298
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 154.75401166195195,
        "scoreError": 10.099746664512518,
        "scoreConfidence": [
          144.65426499743944,
          164.85375832646446
        ],
        "scorePercentiles": {
          "0.0": 151.52622345099226,
          "50.0": 154.66591589363017,
          "90.0": 157.72982954903816,
          "95.0": 157.72982954903816,
          "99.0": 157.72982954903816,
          "99.9": 157.72982954903816,
          "99.99": 157.72982954903816,
          "99.999": 157.72982954903816,
          "99.9999": 157.72982954903816,
          "100.0": 157.72982954903816
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            154.66591589363017,
            152.90189970952454,
            151.52622345099226,
            156.94618970657461,
            157.72982954903816
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 312.20248146817283,
        "scoreError": 2.536423318520105,
        "scoreConfidence": [
          309.6660581496527,
          314.73890478669296
        ],
        "scorePercentiles": {
          "0.0": 311.41433655043585,
          "50.0": 312.1925696004994,
          "90.0": 313.1515948653726,
          "95.0": 313.1515948653726,
          "99.0": 313.1515948653726,
          "99.9": 313.1515948653726,
          "99.99": 313.1515948653726,
          "99.999": 313.1515948653726,
          "99.9999": 313.1515948653726,
          "100.0": 313.1515948653726
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            312.4447994376757,
            312.1925696004994,
            311.80910688688067,
            313.1515948653726,
            311.41433655043585
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 365.3624113061531,
        "scoreError": 8.954802138103767,
        "scoreConfidence": [
          356.4076091680493,
          374.3172134442569
        ],
        "scorePercentiles": {
          "0.0": 362.2753141512848,
          "50.0": 365.2901953981008,
          "90.0": 368.79631809804647,
          "95.0": 368.79631809804647,
          "99.0": 368.79631809804647,
          "99.9": 368.79631809804647,
          "99.99": 368.79631809804647,
          "99.999": 368.79631809804647,
          "99.9999": 368.79631809804647,
          "100.0": 368.79631809804647
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            365.2901953981008,
            365.5909196200219,
            364.85930926331145,
            368.79631809804647,
            362.2753141512848
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "linuxX64": [
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 958.3300187192119,
        "scoreError": 8.593169727516928,
        "scoreConfidence": [
          949.736848991695,
          966.9231884467289
        ],
        "scorePercentiles": {
          "0.00": 948.5866216748769,
          "25.00": 948.8311891625617,
          "50.00": 960.5236965517241,
          "75.00": 966.7320093596059,
          "90.00": 972.1107753694581,
          "99.00": 972.1107753694581,
          "99.90": 972.1107753694581,
          "99.99": 972.1107753694581,
          "100.00": 972.1107753694581
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            948.5866216748769,
            949.0757566502464,
            972.1107753694581,
            960.5236965517241,
            961.3532433497537
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 877.741338251366,
        "scoreError": 4.3600730678280195,
        "scoreConfidence": [
          873.381265183538,
          882.101411319194
        ],
        "scorePercentiles": {
          "0.00": 870.8060409836066,
          "25.00": 873.3744508196721,
          "50.00": 877.9687805100182,
          "75.00": 881.994504553734,
          "90.00": 884.3827012750455,
          "99.00": 884.3827012750455,
          "99.90": 884.3827012750455,
          "99.99": 884.3827012750455,
          "100.00": 884.3827012750455
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            879.6063078324225,
            870.8060409836066,
            884.3827012750455,
            875.9428606557377,
            877.9687805100182
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2534.1030927083334,
        "scoreError": 17.886408925667002,
        "scoreConfidence": [
          2516.216683782666,
          2551.9895016340006
        ],
        "scorePercentiles": {
          "0.00": 2518.4061197916667,
          "25.00": 2518.905532552083,
          "50.00": 2524.9666302083333,
          "75.00": 2553.8688841145836,
          "90.00": 2566.8745833333337,
          "99.00": 2566.8745833333337,
          "99.90": 2566.8745833333337,
          "99.99": 2566.8745833333337,
          "100.00": 2566.8745833333337
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2519.4049453125,
            2518.4061197916667,
            2566.8745833333337,
            2540.8631848958335,
            2524.9666302083333
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2649.101179624665,
        "scoreError": 8.26379918178068,
        "scoreConfidence": [
          2640.8373804428843,
          2657.3649788064454
        ],
        "scorePercentiles": {
          "0.00": 2637.5898042895446,
          "25.00": 2641.308627345845,
          "50.00": 2645.2791554959786,
          "75.00": 2658.8047439678285,
          "90.00": 2660.12718230563,
          "99.00": 2660.12718230563,
          "99.90": 2660.12718230563,
          "99.99": 2660.12718230563,
          "100.00": 2660.12718230563
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2645.027450402145,
            2660.12718230563,
            2637.5898042895446,
            2645.2791554959786,
            2657.482305630027
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
