// provided.js - generated by ephemient/aoc2024/Kotlin benchmarks, 2024-12-04 07:17:08.734937588

var providedBenchmarks = ["graalvm","jvm","linuxX64","wasmJs"];

var providedBenchmarkStore = {
  "linuxX64": [
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1027.2536874200428,
        "scoreError": 17.3035548688846,
        "scoreConfidence": [
          1009.9501325511582,
          1044.5572422889275
        ],
        "scorePercentiles": {
          "0.00": 993.6144893390192,
          "25.00": 1010.585447228145,
          "50.00": 1034.4917793176974,
          "75.00": 1040.302881663113,
          "90.00": 1044.4352579957356,
          "99.00": 1044.4352579957356,
          "99.90": 1044.4352579957356,
          "99.99": 1044.4352579957356,
          "100.00": 1044.4352579957356
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1034.4917793176974,
            1044.4352579957356,
            1027.5564051172707,
            993.6144893390192,
            1036.1705053304904
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 883.1500587500001,
        "scoreError": 7.277942175151433,
        "scoreConfidence": [
          875.8721165748486,
          890.4280009251515
        ],
        "scorePercentiles": {
          "0.00": 878.9222473214286,
          "25.00": 879.0024401785714,
          "50.00": 879.3081491071429,
          "75.00": 889.2186321428571,
          "90.00": 897.9630196428571,
          "99.00": 897.9630196428571,
          "99.90": 897.9630196428571,
          "99.99": 897.9630196428571,
          "100.00": 897.9630196428571
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            879.3081491071429,
            878.9222473214286,
            880.4742446428571,
            879.0826330357143,
            897.9630196428571
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2613.5462564885497,
        "scoreError": 58.9578442611909,
        "scoreConfidence": [
          2554.5884122273587,
          2672.5041007497407
        ],
        "scorePercentiles": {
          "0.00": 2565.7366946564885,
          "25.00": 2568.202723918575,
          "50.00": 2576.1416412213744,
          "75.00": 2677.592096692112,
          "90.00": 2724.3344223918575,
          "99.00": 2724.3344223918575,
          "99.90": 2724.3344223918575,
          "99.99": 2724.3344223918575,
          "100.00": 2724.3344223918575
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2570.6687531806615,
            2630.8497709923668,
            2565.7366946564885,
            2576.1416412213744,
            2724.3344223918575
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2673.521283646113,
        "scoreError": 22.447548926606146,
        "scoreConfidence": [
          2651.073734719507,
          2695.968832572719
        ],
        "scorePercentiles": {
          "0.00": 2649.219324396783,
          "25.00": 2651.179981233244,
          "50.00": 2666.3524986595176,
          "75.00": 2699.446978552279,
          "90.00": 2709.975892761394,
          "99.00": 2709.975892761394,
          "99.90": 2709.975892761394,
          "99.99": 2709.975892761394,
          "100.00": 2709.975892761394
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2666.3524986595176,
            2649.219324396783,
            2653.140638069705,
            2688.9180643431637,
            2709.975892761394
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 725.9136819720383,
        "scoreError": 11.473082587384233,
        "scoreConfidence": [
          714.440599384654,
          737.3867645594225
        ],
        "scorePercentiles": {
          "0.00": 710.039493745401,
          "25.00": 715.8430191317145,
          "50.00": 724.3269580573951,
          "75.00": 736.7777067696836,
          "90.00": 746.1725393671817,
          "99.00": 746.1725393671817,
          "99.90": 746.1725393671817,
          "99.99": 746.1725393671817,
          "100.00": 746.1725393671817
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            721.6465445180279,
            727.3828741721854,
            746.1725393671817,
            710.039493745401,
            724.3269580573951
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 463.89908255867465,
        "scoreError": 0.6105960232536416,
        "scoreConfidence": [
          463.288486535421,
          464.5096785819283
        ],
        "scorePercentiles": {
          "0.00": 462.7576355269213,
          "25.00": 463.29568016566964,
          "50.00": 464.0162774965485,
          "75.00": 464.44388748274275,
          "90.00": 464.55892820984815,
          "99.00": 464.55892820984815,
          "99.90": 464.55892820984815,
          "99.99": 464.55892820984815,
          "100.00": 464.55892820984815
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            462.7576355269213,
            464.55892820984815,
            464.0162774965485,
            464.32884675563736,
            463.8337248044179
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 15267.567027272726,
        "scoreError": 475.8632385460987,
        "scoreConfidence": [
          14791.703788726627,
          15743.430265818824
        ],
        "scorePercentiles": {
          "0.00": 14550.779636363637,
          "25.00": 14780.875393939394,
          "50.00": 15157.482833333333,
          "75.00": 15809.300757575757,
          "90.00": 15819.767409090908,
          "99.00": 15819.767409090908,
          "99.90": 15819.767409090908,
          "99.99": 15819.767409090908,
          "100.00": 15819.767409090908
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            15798.834106060605,
            15819.767409090908,
            15157.482833333333,
            14550.779636363637,
            15010.971151515152
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 488.78598356164383,
        "scoreError": 2.1477911730695234,
        "scoreConfidence": [
          486.6381923885743,
          490.9337747347134
        ],
        "scorePercentiles": {
          "0.00": 486.65358904109587,
          "25.00": 487.049614481409,
          "50.00": 488.0252656555773,
          "75.00": 490.9027115949119,
          "90.00": 492.9192279843444,
          "99.00": 492.9192279843444,
          "99.90": 492.9192279843444,
          "99.99": 492.9192279843444,
          "100.00": 492.9192279843444
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            486.65358904109587,
            487.4456399217221,
            492.9192279843444,
            488.0252656555773,
            488.88619520547945
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "wasmJs": [
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1190.0695156410256,
        "scoreError": 24.037737265425537,
        "scoreConfidence": [
          1166.0317783756002,
          1214.107252906451
        ],
        "scorePercentiles": {
          "0.00": 1177.5725794871794,
          "25.00": 1177.5760282051283,
          "50.00": 1177.896864102564,
          "75.00": 1208.6493288461538,
          "90.00": 1239.1240846153846,
          "99.00": 1239.1240846153846,
          "99.90": 1239.1240846153846,
          "99.99": 1239.1240846153846,
          "100.00": 1239.1240846153846
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1239.1240846153846,
            1177.896864102564,
            1177.579476923077,
            1177.5725794871794,
            1178.1745730769233
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 1063.2317961456101,
        "scoreError": 8.237255453175866,
        "scoreConfidence": [
          1054.9945406924342,
          1071.469051598786
        ],
        "scorePercentiles": {
          "0.00": 1053.9251209850106,
          "25.00": 1056.585107601713,
          "50.00": 1059.2459593147753,
          "75.00": 1071.8714031049249,
          "90.00": 1078.412431477516,
          "99.00": 1078.412431477516,
          "99.90": 1078.412431477516,
          "99.99": 1078.412431477516,
          "100.00": 1078.412431477516
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1065.330374732334,
            1059.2450942184155,
            1059.2459593147753,
            1053.9251209850106,
            1078.412431477516
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2560.8072907216497,
        "scoreError": 13.602445206972261,
        "scoreConfidence": [
          2547.2048455146773,
          2574.409735928622
        ],
        "scorePercentiles": {
          "0.00": 2548.7794793814433,
          "25.00": 2549.943175257732,
          "50.00": 2555.3167345360825,
          "75.00": 2574.4166842783507,
          "90.00": 2587.1433221649486,
          "99.00": 2587.1433221649486,
          "99.90": 2587.1433221649486,
          "99.99": 2587.1433221649486,
          "100.00": 2587.1433221649486
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2555.3167345360825,
            2561.6900463917527,
            2587.1433221649486,
            2548.7794793814433,
            2551.1068711340204
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 2711.921900271003,
        "scoreError": 17.70539973198622,
        "scoreConfidence": [
          2694.2165005390166,
          2729.627300002989
        ],
        "scorePercentiles": {
          "0.00": 2689.680208672087,
          "25.00": 2694.385138211382,
          "50.00": 2709.064406504065,
          "75.00": 2730.8874092140923,
          "90.00": 2741.9585284552845,
          "99.00": 2741.9585284552845,
          "99.90": 2741.9585284552845,
          "99.99": 2741.9585284552845,
          "100.00": 2741.9585284552845
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            2719.8162899729,
            2741.9585284552845,
            2709.064406504065,
            2699.0900677506775,
            2689.680208672087
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 908.9862421731125,
        "scoreError": 2.7370324847866625,
        "scoreConfidence": [
          906.2492096883258,
          911.7232746578992
        ],
        "scorePercentiles": {
          "0.00": 903.9538268876611,
          "25.00": 906.1918816758748,
          "50.00": 909.9795405156538,
          "75.00": 911.2839534990792,
          "90.00": 912.2381298342542,
          "99.00": 912.2381298342542,
          "99.90": 912.2381298342542,
          "99.99": 912.2381298342542,
          "100.00": 912.2381298342542
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            909.9795405156538,
            903.9538268876611,
            912.2381298342542,
            908.4299364640884,
            910.3297771639043
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 832.2946132983377,
        "scoreError": 1.6085592197198084,
        "scoreConfidence": [
          830.6860540786179,
          833.9031725180575
        ],
        "scorePercentiles": {
          "0.00": 831.0114418197725,
          "25.00": 831.1965030621172,
          "50.00": 831.7265783027121,
          "75.00": 833.676741032371,
          "90.00": 835.5270586176728,
          "99.00": 835.5270586176728,
          "99.90": 835.5270586176728,
          "99.99": 835.5270586176728,
          "100.00": 835.5270586176728
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            831.3815643044619,
            831.0114418197725,
            831.7265783027121,
            835.5270586176728,
            831.8264234470691
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 14680.456086567163,
        "scoreError": 33.48752992361251,
        "scoreConfidence": [
          14646.968556643551,
          14713.943616490775
        ],
        "scorePercentiles": {
          "0.00": 14623.521343283583,
          "25.00": 14648.027402985073,
          "50.00": 14681.977641791045,
          "75.00": 14712.123992537312,
          "90.00": 14728.339850746268,
          "99.00": 14728.339850746268,
          "99.90": 14728.339850746268,
          "99.99": 14728.339850746268,
          "100.00": 14728.339850746268
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            14623.521343283583,
            14728.339850746268,
            14672.533462686566,
            14681.977641791045,
            14695.908134328358
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 5,
      "measurementTime": "1 sec",
      "params": {},
      "advanced": {},
      "primaryMetric": {
        "score": 573.5332043778801,
        "scoreError": 1.1521593764782607,
        "scoreConfidence": [
          572.3810450014018,
          574.6853637543584
        ],
        "scorePercentiles": {
          "0.00": 572.1938271889402,
          "25.00": 572.4122137096774,
          "50.00": 573.6097407834102,
          "75.00": 574.615926843318,
          "90.00": 575.6038473502305,
          "99.00": 575.6038473502305,
          "99.90": 575.6038473502305,
          "99.99": 575.6038473502305,
          "100.00": 575.6038473502305
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            573.6280063364055,
            573.6097407834102,
            572.6306002304148,
            572.1938271889402,
            575.6038473502305
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "graalvm": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 472.4352479643705,
        "scoreError": 32.88127092207002,
        "scoreConfidence": [
          439.55397704230046,
          505.3165188864405
        ],
        "scorePercentiles": {
          "0.0": 457.65116239707226,
          "50.0": 476.20257924797716,
          "90.0": 478.8868870272858,
          "95.0": 478.8868870272858,
          "99.0": 478.8868870272858,
          "99.9": 478.8868870272858,
          "99.99": 478.8868870272858,
          "99.999": 478.8868870272858,
          "99.9999": 478.8868870272858,
          "100.0": 478.8868870272858
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            457.65116239707226,
            478.8868870272858,
            476.57028632682227,
            472.865324822695,
            476.20257924797716
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 337.44392488562215,
        "scoreError": 15.219751917630758,
        "scoreConfidence": [
          322.2241729679914,
          352.6636768032529
        ],
        "scorePercentiles": {
          "0.0": 333.5692364121374,
          "50.0": 336.94086493768947,
          "90.0": 343.96697696011006,
          "95.0": 343.96697696011006,
          "99.0": 343.96697696011006,
          "99.9": 343.96697696011006,
          "99.99": 343.96697696011006,
          "99.999": 343.96697696011006,
          "99.9999": 343.96697696011006,
          "100.0": 343.96697696011006
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            336.94086493768947,
            337.46031950067476,
            335.28222661749913,
            333.5692364121374,
            343.96697696011006
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 664.3219096200631,
        "scoreError": 11.122076263188598,
        "scoreConfidence": [
          653.1998333568746,
          675.4439858832517
        ],
        "scorePercentiles": {
          "0.0": 661.2388420356907,
          "50.0": 663.0931106693174,
          "90.0": 668.7444465240642,
          "95.0": 668.7444465240642,
          "99.0": 668.7444465240642,
          "99.9": 668.7444465240642,
          "99.99": 668.7444465240642,
          "99.999": 668.7444465240642,
          "99.9999": 668.7444465240642,
          "100.0": 668.7444465240642
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            663.0931106693174,
            661.2388420356907,
            665.4477744510978,
            668.7444465240642,
            663.0853744201457
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 716.776991503448,
        "scoreError": 9.85145003915087,
        "scoreConfidence": [
          706.9255414642971,
          726.6284415425989
        ],
        "scorePercentiles": {
          "0.0": 714.5361371428571,
          "50.0": 716.536755730659,
          "90.0": 720.7315929394813,
          "95.0": 720.7315929394813,
          "99.0": 720.7315929394813,
          "99.9": 720.7315929394813,
          "99.99": 720.7315929394813,
          "99.999": 720.7315929394813,
          "99.9999": 720.7315929394813,
          "100.0": 720.7315929394813
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            714.5361371428571,
            716.536755730659,
            720.7315929394813,
            714.5607407142858,
            717.519730989957
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 207.9718194207997,
        "scoreError": 2.9944657405216786,
        "scoreConfidence": [
          204.97735368027801,
          210.9662851613214
        ],
        "scorePercentiles": {
          "0.0": 207.2499069622876,
          "50.0": 207.61327251971773,
          "90.0": 208.90305472013367,
          "95.0": 208.90305472013367,
          "99.0": 208.90305472013367,
          "99.9": 208.90305472013367,
          "99.99": 208.90305472013367,
          "99.999": 208.90305472013367,
          "99.9999": 208.90305472013367,
          "100.0": 208.90305472013367
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            207.37899917064067,
            207.2499069622876,
            208.90305472013367,
            207.61327251971773,
            208.7138637312187
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 132.77387816995207,
        "scoreError": 1.557318221688948,
        "scoreConfidence": [
          131.21655994826313,
          134.33119639164101
        ],
        "scorePercentiles": {
          "0.0": 132.28498849510711,
          "50.0": 132.60894764744864,
          "90.0": 133.23068575995737,
          "95.0": 133.23068575995737,
          "99.0": 133.23068575995737,
          "99.9": 133.23068575995737,
          "99.99": 133.23068575995737,
          "99.999": 133.23068575995737,
          "99.9999": 133.23068575995737,
          "100.0": 133.23068575995737
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            133.15519278391693,
            132.58957616333024,
            132.60894764744864,
            133.23068575995737,
            132.28498849510711
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4944.860720345564,
        "scoreError": 118.31778639796457,
        "scoreConfidence": [
          4826.5429339475995,
          5063.1785067435285
        ],
        "scorePercentiles": {
          "0.0": 4904.96287745098,
          "50.0": 4957.140341584159,
          "90.0": 4974.411782178217,
          "95.0": 4974.411782178217,
          "99.0": 4974.411782178217,
          "99.9": 4974.411782178217,
          "99.99": 4974.411782178217,
          "99.999": 4974.411782178217,
          "99.9999": 4974.411782178217,
          "100.0": 4974.411782178217
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            4904.96287745098,
            4957.140341584159,
            4974.411782178217,
            4967.964752475247,
            4919.823848039216
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "21.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "21.0.5+9-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 375.41323894476943,
        "scoreError": 15.550666106703957,
        "scoreConfidence": [
          359.8625728380655,
          390.9639050514734
        ],
        "scorePercentiles": {
          "0.0": 371.5567737741456,
          "50.0": 374.35220134730537,
          "90.0": 382.2607634696217,
          "95.0": 382.2607634696217,
          "99.0": 382.2607634696217,
          "99.9": 382.2607634696217,
          "99.99": 382.2607634696217,
          "99.999": 382.2607634696217,
          "99.9999": 382.2607634696217,
          "100.0": 382.2607634696217
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            371.5567737741456,
            382.2607634696217,
            373.9545768224299,
            374.35220134730537,
            374.9418793103448
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvm": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 284.83145013260923,
        "scoreError": 4.90419098136418,
        "scoreConfidence": [
          279.92725915124504,
          289.73564111397343
        ],
        "scorePercentiles": {
          "0.0": 282.7981540853831,
          "50.0": 284.95541452991455,
          "90.0": 286.2848477142857,
          "95.0": 286.2848477142857,
          "99.0": 286.2848477142857,
          "99.9": 286.2848477142857,
          "99.99": 286.2848477142857,
          "99.999": 286.2848477142857,
          "99.9999": 286.2848477142857,
          "100.0": 286.2848477142857
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            286.2848477142857,
            285.306696520251,
            282.7981540853831,
            284.81213781321185,
            284.95541452991455
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day1Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 154.19517071010273,
        "scoreError": 17.442839169635327,
        "scoreConfidence": [
          136.7523315404674,
          171.63800987973806
        ],
        "scorePercentiles": {
          "0.0": 151.83435230722526,
          "50.0": 151.9976207263334,
          "90.0": 162.25119318734792,
          "95.0": 162.25119318734792,
          "99.0": 162.25119318734792,
          "99.9": 162.25119318734792,
          "99.99": 162.25119318734792,
          "99.999": 162.25119318734792,
          "99.9999": 162.25119318734792,
          "100.0": 162.25119318734792
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            162.25119318734792,
            151.87224339508046,
            151.9976207263334,
            151.83435230722526,
            153.02044393452655
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 319.05379827410997,
        "scoreError": 7.689519496625994,
        "scoreConfidence": [
          311.36427877748395,
          326.743317770736
        ],
        "scorePercentiles": {
          "0.0": 317.0902643423138,
          "50.0": 318.98485204081635,
          "90.0": 322.15427003540395,
          "95.0": 322.15427003540395,
          "99.0": 322.15427003540395,
          "99.9": 322.15427003540395,
          "99.99": 322.15427003540395,
          "99.999": 322.15427003540395,
          "99.9999": 322.15427003540395,
          "100.0": 322.15427003540395
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            319.49645257106357,
            317.5431523809524,
            322.15427003540395,
            317.0902643423138,
            318.98485204081635
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day2Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 362.69212387390525,
        "scoreError": 15.706623434536706,
        "scoreConfidence": [
          346.98550043936854,
          378.39874730844195
        ],
        "scorePercentiles": {
          "0.0": 358.3684632748119,
          "50.0": 361.52828478496565,
          "90.0": 369.16837993360383,
          "95.0": 369.16837993360383,
          "99.0": 369.16837993360383,
          "99.9": 369.16837993360383,
          "99.99": 369.16837993360383,
          "99.999": 369.16837993360383,
          "99.9999": 369.16837993360383,
          "100.0": 369.16837993360383
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            361.52828478496565,
            363.6246990185387,
            358.3684632748119,
            360.77079235760635,
            369.16837993360383
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 119.61852761177889,
        "scoreError": 2.1839899913901917,
        "scoreConfidence": [
          117.4345376203887,
          121.80251760316908
        ],
        "scorePercentiles": {
          "0.0": 119.06777761904762,
          "50.0": 119.47962143113129,
          "90.0": 120.57854828209764,
          "95.0": 120.57854828209764,
          "99.0": 120.57854828209764,
          "99.9": 120.57854828209764,
          "99.99": 120.57854828209764,
          "99.999": 120.57854828209764,
          "99.9999": 120.57854828209764,
          "100.0": 120.57854828209764
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            120.57854828209764,
            119.06777761904762,
            119.53785442811044,
            119.47962143113129,
            119.42883629850746
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day3Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 83.81822860681011,
        "scoreError": 1.4950114163820507,
        "scoreConfidence": [
          82.32321719042805,
          85.31324002319217
        ],
        "scorePercentiles": {
          "0.0": 83.49499198597546,
          "50.0": 83.56310318918017,
          "90.0": 84.26236377422073,
          "95.0": 84.26236377422073,
          "99.0": 84.26236377422073,
          "99.9": 84.26236377422073,
          "99.99": 84.26236377422073,
          "99.999": 84.26236377422073,
          "99.9999": 84.26236377422073,
          "100.0": 84.26236377422073
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            84.22232572631579,
            84.26236377422073,
            83.49499198597546,
            83.54835835835836,
            83.56310318918017
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part1",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1936.838171043007,
        "scoreError": 31.248279842400997,
        "scoreConfidence": [
          1905.589891200606,
          1968.0864508854079
        ],
        "scorePercentiles": {
          "0.0": 1931.0618146718148,
          "50.0": 1931.6600598455598,
          "90.0": 1949.5940894941634,
          "95.0": 1949.5940894941634,
          "99.0": 1949.5940894941634,
          "99.9": 1949.5940894941634,
          "99.99": 1949.5940894941634,
          "99.999": 1949.5940894941634,
          "99.9999": 1949.5940894941634,
          "100.0": 1949.5940894941634
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            1940.3478217054264,
            1931.0618146718148,
            1931.5270694980695,
            1931.6600598455598,
            1949.5940894941634
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2024.exe.Day4Bench.part2",
      "mode": "avgt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-21-jdk-amd64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "21.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "21.0.5+11-LTS",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 240.8983391472431,
        "scoreError": 9.076749764776908,
        "scoreConfidence": [
          231.8215893824662,
          249.97508891202
        ],
        "scorePercentiles": {
          "0.0": 238.36995352716872,
          "50.0": 241.11615573770493,
          "90.0": 243.64282314250914,
          "95.0": 243.64282314250914,
          "99.0": 243.64282314250914,
          "99.9": 243.64282314250914,
          "99.99": 243.64282314250914,
          "99.999": 243.64282314250914,
          "99.9999": 243.64282314250914,
          "100.0": 243.64282314250914
        },
        "scoreUnit": "us/op",
        "rawData": [
          [
            241.11615573770493,
            238.66159031257456,
            242.7011730162582,
            238.36995352716872,
            243.64282314250914
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
