name: Haskell benchmarks

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get-inputs:
    uses: ephemient/aoc2024/.github/workflows/get-inputs.yml@main
    secrets:
      SESSION: ${{ secrets.SESSION }}

  build:
    needs: [ get-inputs ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '9.10', '9.12' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: inputs
          path: inputs
      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: |
          cabal configure --enable-tests --enable-benchmarks --with-compiler=ghc-${{ matrix.ghc }} --allow-newer=aeson-2.2.3.0:ghc-prim,aeson-2.2.3.0:template-haskell,binary-orphans-1.0.5:base,indexed-traversable-0.1.4:base,indexed-traversable-instances-0.1.2:base,integer-conversion-0.1.1:base,microstache-1.0.3:base,process-1.6.25.0:base,process-1.6.25.0:filepath,scientific-0.3.8.0:base,scientific-0.3.8.0:filepath,scientific-0.3.8.0:template-haskell,semialign-1.3.1:base,these-1.2.1:base,time-compat-1.9.7:base,uuid-types-1.0.6:template-haskell
          cabal build all --dry-run
        working-directory: hs
      - uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('hs/dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ env.key }}-
      - run: cabal build all --only-dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: hs
      - uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - run: cabal bench bench:aoc2024-bench --benchmark-options='-o aoc2024-bench.html'
        env:
          AOC2024_DATADIR: ${{ github.workspace }}/inputs
          TRACE: 0
        working-directory: hs
      - uses: actions/upload-artifact@v4
        with:
          name: ghc-${{ matrix.ghc }}
          path: hs/aoc2024-bench.html

  docs:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-docs
      - uses: actions/download-artifact@v4
        with:
          name: ghc-9.10
      - uses: actions/download-artifact@v4
        with:
          name: ghc-9.12
          path: aoc2024-bench-9.12.html
      - run: |
          git add aoc2024-bench.html aoc2024-bench-9.12.html
          git commit -m 'Haskell Criterion ${{ github.sha }}'
          git push
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
