name: Haskell CI

on:
  push:
    branches: [ main ]
    paths: [ hs/**, .github/workflows/hs.yml ]
  pull_request:
    branches: [ main ]
    paths: [ hs/**, .github/workflows/hs.yml ]

  workflow_dispatch:

jobs:
  get-inputs:
    uses: ephemient/aoc2024/.github/workflows/get-inputs.yml@main
    secrets:
      SESSION: ${{ secrets.SESSION }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: 9.10.1
      - run: |
          cabal configure --enable-tests --enable-benchmarks
          cabal build all --dry-run
        working-directory: hs
      - uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('hs/dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ env.key }}-
      - run: cabal build all --only-dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: hs
      - uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - id: build
        run: |
          cabal build all
          echo "exe=$(cabal list-bin aoc2024)" >> $GITHUB_OUTPUT
        working-directory: hs
      - run: cabal test all --test-show-details=direct
        working-directory: hs
      - run: cabal check
        working-directory: hs
      - uses: actions/upload-artifact@v4
        with:
          name: aoc2024-hs
          path: ${{ steps.build.outputs.exe }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
          path: hs
      - uses: haskell-actions/run-ormolu@v16
        with:
          extra-args: --ghc-opt -XGHC2024
          pattern: |
            hs/**/*.hs
            hs/**/*.hs-boot
      - uses: tfausak/cabal-gild-setup-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: cabal-gild --input hs/aoc2024.cabal --mode check

  run:
    needs: [ get-inputs, build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
      - run: chmod +x aoc2024-hs/aoc2024
      - run: aoc2024-hs/aoc2024
        env:
          AOC2024_DATADIR: inputs
