name: Haskell CI

on:
  push:
    branches: [ main ]
    paths: [ hs/**, .github/workflows/hs.yml ]
  pull_request:
    branches: [ main ]
    paths: [ hs/**, .github/workflows/hs.yml ]

  workflow_dispatch:

jobs:
  get-inputs:
    uses: ephemient/aoc2024/.github/workflows/get-inputs.yml@main
    secrets:
      SESSION: ${{ secrets.SESSION }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '9.10', '9.12' ]

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: |
          cabal configure --enable-tests --enable-benchmarks --with-compiler=ghc-${{ matrix.ghc }} --allow-newer=aeson-2.2.3.0:ghc-prim,aeson-2.2.3.0:template-haskell,binary-orphans-1.0.5:base,indexed-traversable-0.1.4:base,indexed-traversable-instances-0.1.2:base,integer-conversion-0.1.1:base,microstache-1.0.3:base,process-1.6.25.0:base,process-1.6.25.0:filepath,scientific-0.3.8.0:base,scientific-0.3.8.0:filepath,scientific-0.3.8.0:template-haskell,semialign-1.3.1:base,these-1.2.1:base,time-compat-1.9.7:base,uuid-types-1.0.6:template-haskell
          cabal build all --dry-run
        working-directory: hs
      - uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('hs/dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ env.key }}-
      - run: cabal build all --only-dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: hs
      - uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - id: build
        run: |
          cabal build all
          echo "exe=$(cabal list-bin aoc2024)" >> $GITHUB_OUTPUT
        working-directory: hs
      - run: cabal test all
        working-directory: hs
      - run: cabal check
        working-directory: hs
      - uses: actions/upload-artifact@v4
        with:
          name: aoc2024-hs-${{ matrix.ghc }}
          path: ${{ steps.build.outputs.exe }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
          path: hs
      - uses: haskell-actions/run-ormolu@v16
        with:
          extra-args: --ghc-opt -XGHC2024
          pattern: |
            hs/**/*.hs
            hs/**/*.hs-boot
      - uses: tfausak/cabal-gild-setup-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: cabal-gild --input hs/aoc2024.cabal --mode check

  run:
    needs: [ get-inputs, build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
      - run: chmod +x aoc2024-hs-9.10/aoc2024 aoc2024-hs-9.12/aoc2024
      - run: aoc2024-hs-9.10/aoc2024
        env:
          AOC2024_DATADIR: inputs
      - run: aoc2024-hs-9.12/aoc2024
        env:
          AOC2024_DATADIR: inputs
