package com.github.ephemient.aoc2024

import kotlin.test.Test
import kotlin.test.assertEquals

class Day8Test {
    @Test
    fun part1() {
        assertEquals(14, Day8(example).part1())
    }

    @Test
    fun part2() {
        assertEquals(34, Day8(example).part2())
    }

    companion object {
        private val example =
            """
            |............
            |........0...
            |.....0......
            |.......0....
            |....0.......
            |......A.....
            |............
            |............
            |........A...
            |.........A..
            |............
            |............
            |""".trimMargin()
    }
}
